version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: |
            sudo apt-get update && apt-get install clang
      - run:
          name: "Build using Maven"
          command: |
            mvn -B clean package
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}      
